version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/uploads
    environment:
      - UPLOAD_DIR=/uploads
      - MAX_FILE_SIZE=1000000000
    networks:
      - my-app-network

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
      - GET_URL=http://localhost:8000
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge