import os

API_KEY = "NzRjMTFhOTYtNWM2Ny00YTg0LWJiYzYtNzg2OGNhYWY2NzZkOjNjYTQ5OWQ5LWQyOGMtNDFhOC1hYWJmLWIwYWZlZDUxY2VkYw=="
MAX_RETRIES = 3
DELAY_BETWEEN_REQUESTS = 10
UPLOAD_DIR = os.getenv("UPLOAD_DIR", "uploads")
OUTPUT_AUDIO_PATH = "output_audio.wav"