import os

API_KEY = "NmE2MWQ5MTctOTQ3ZC00ZGI5LWIwODMtMGIxOTNkY2FiYzI5OjI3NTJjMzQwLWQ1NTMtNGJlNy1iMzI4LWE3YTMyYTA2NTNmYQ=="
MAX_RETRIES = 3
DELAY_BETWEEN_REQUESTS = 10
UPLOAD_DIR = os.getenv("UPLOAD_DIR", "uploads")
OUTPUT_AUDIO_PATH = "output_audio.wav"